# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cy = {
    pname = "cy";
    version = "f62c45681a4a6452af82a6d02e3f46cec951506c";
    src = fetchgit {
      url = "https://github.com/cycloidio/cycloid-cli.git";
      rev = "f62c45681a4a6452af82a6d02e3f46cec951506c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ho83hQ+Om5IqfWUnv0blQ6YWoZdHcJJiwZbkn8GoKRo=";
    };
    date = "2024-03-26";
  };
}
